apiVersion: v2
name: git-hubby
description: Helm chart for the git-hubby Kubernetes operator — manage GitHub resources declaratively via CRDs
type: application
version: 0.0.1
appVersion: "snapshot-renovate-docker-setup-qemu-action-4.x-ab16a57"
home: https://github.com/Interhyp/git-hubby-helm
sources:
  - https://github.com/Interhyp/git-hubby-helm
  - https://github.com/Interhyp/git-hubby
maintainers:
  - name: Interhyp Technical Excellence
    url: https://github.com/Interhyp
keywords:
  - github
  - operator
  - kubernetes
  - gitops
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/operator: "true"
