apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-hubby.fullname" . }}-envs
  labels:
  {{- include "git-hubby.labels" . | nindent 4 }}
{{ if .Values.envs }}
data:
  {{ range $key, $value := .Values.envs }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}
{{ else }}
data: {}
{{ end }}
