apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-envs
  labels:
  {{- include "chart.labels" . | nindent 4 }}
{{ if .Values.envs }}
data:
  {{ range $key, $value := .Values.envs }}
  {{ $key }}: {{ $value | quote }}
  {{ end }}
{{ else }}
data: {}
{{ end }}
