apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "git-hubby.fullname" . }}-metrics-certs
  labels:
  {{- include "git-hubby.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "git-hubby.fullname" . }}-controller-manager-metrics-service.{{ .Release.Namespace
    }}.svc'
  - '{{ include "git-hubby.fullname" . }}-controller-manager-metrics-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  secretName: metrics-server-cert
  {{- with .Values.metricsCert.duration }}
  duration: {{ . }}
  {{- end }}
  issuerRef:
    {{- if .Values.metricsCert.issuerRef }}
    {{- toYaml .Values.metricsCert.issuerRef | nindent 4 }}
    {{- else if .Values.selfSignedIssuer.enabled }}
    kind: Issuer
    name: {{ include "git-hubby.selfSignedIssuerName" . }}
    {{- else }}
    {{- fail "metricsCert.issuerRef must be set when selfSignedIssuer.enabled is false" }}
    {{- end }}
  {{- with .Values.metricsCert.privateKey }}
  privateKey:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metricsCert.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
  {{- with .Values.metricsCert.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{- end }}
