apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "git-hubby.fullname" . }}-repository-admin-role
  labels:
  {{- include "git-hubby.labels" . | nindent 4 }}
rules:
- apiGroups:
  - github.interhyp.de
  resources:
  - repositories
  verbs:
  - '*'
- apiGroups:
  - github.interhyp.de
  resources:
  - repositories/status
  verbs:
  - get
