apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "git-hubby.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "git-hubby.labels" . | nindent 4 }}
spec:
  selfSigned: {}
