apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "git-hubby.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "git-hubby.fullname" . }}-serving-cert
  labels:
  {{- include "git-hubby.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "git-hubby.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-github-interhyp-de-v1alpha1-organization
  failurePolicy: Fail
  name: vorganization-v1alpha1.kb.io
  {{- include "git-hubby.webhookNamespaceSelector" . | nindent 2 }}
  rules:
  - apiGroups:
    - github.interhyp.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - organizations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "git-hubby.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-github-interhyp-de-v1alpha1-repository
  failurePolicy: Fail
  name: vrepository-v1alpha1.kb.io
  {{- include "git-hubby.webhookNamespaceSelector" . | nindent 2 }}
  rules:
  - apiGroups:
    - github.interhyp.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
