{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "git-hubby.fullname" . }}-webhook-service
  labels:
  {{- include "git-hubby.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
    {{- include "git-hubby.selectorLabels" . | nindent 4 }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: webhook-server
{{- end }}
