apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chart.fullname" . }}-webhookpreset-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - github.interhyp.de
  resources:
  - webhookpresets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.interhyp.de
  resources:
  - webhookpresets/status
  verbs:
  - get
