name: CI
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - &setup_helm
        name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
      - name: Lint
        run: helm lint .

  unittest:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_helm
      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git --verify=false
      - name: Test
        run: helm unittest .


  schema:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup_helm
      - name: Install helm-values-schema-json plugin
        run: helm plugin install https://github.com/losisin/helm-values-schema-json.git --verify=false
      - name: Generate values schema json
        uses: losisin/helm-values-schema-json-action@9ed68d9d464a5e6f7f5fc1f3dc071828cf7d13a2 # v3.2.0
        with:
          values: values.yaml
          output: values.schema.json
          fail-on-diff: true